### PR TITLE
Activity.vue: Add multiple action buttons

### PR DESCRIPTION
**Pull request by njordr**
This MR adds multiple action buttons to the Home Page

### CODE REVIEW

**Comment by Bloss** [comment]
https://github.com/njordr/vuepress-theme-yubisaki/blob/master/Activity.vue#L10-L18
I think the actions variable could be named meaningfully. Such as `actions`.
And the code written by this way which the `v-if` judgement in `Activity.vue` change to computed  property could make it more shorter and readable.

**Comment by njordr** [comment]
Something like this could work?

**Comment by Bloss** [comment]
I refactor the code and completed feature/Tag [tags](https://github.com/Bloss/vuepress-theme-yubisaki#tags) , but the code has conflicts with your PR.
So, cloud you please resolve them?

**Comment by Bloss** [comment]
I had some changes about the variable definition, please read [readme-customize-the-layout](https://github.com/Bloss/vuepress-theme-yubisaki#customize-the-layout)

**Pull request merged**
